In [1]:
import pandas as pd

df = pd.read_csv('Ecommerce.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       52 non-null     int64
 1   Gender   52 non-null     object
 2   Country  52 non-null     object
 3   Amount   52 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.8+ KB

In [2]:
df.head()

   Id  Gender Country  Amount
0   1    male     KSA    1500
1   2    male     KSA    2000
2   3    male     KSA    3000
3   4  female  Kuwait    2000
4   5  female     KSA    1000

In [3]:
gr = df.groupby('Amount')
gr.groups

{1000: [4, 9, 14, 19, 23, 25, 29, 31, 34, 35, 37, 41, 46], 1500: [0, 5, 10, 15, 21, 26, 30, 32, 39, 42, 45, 47, 50], 2000: [1, 3, 6, 8, 11, 13, 16, 18, 24, 28, 33, 36, 40, 43, 48, 51], 3000: [2, 7, 12, 17, 20, 22, 27, 38, 44, 49]}

In [4]:
gr.get_group(2000)

    Id  Gender Country  Amount
1    2    male     KSA    2000
3    4  female  Kuwait    2000
6    7    male  Kuwait    2000
8    9    male     UAE    2000
11  12  female  Kuwait    2000
13  14    male     UAE    2000
16  17    male  Kuwait    2000
18  19  female  Kuwait    2000
24  25    male     UAE    2000
28  29    male     UAE    2000
33  34    male     KSA    2000
36  37  female  Kuwait    2000
40  41  female     KSA    2000
43  44  female  Kuwait    2000
48  49  female  Kuwait    2000
51  52  female     KSA    2000

In [5]:
gr = df.groupby(['Country' , 'Gender' , 'Amount'])
for name , gro  in gr:
    print(name)
    print(gro)

('KSA', 'female', np.int64(1000))
    Id  Gender Country  Amount
4    5  female     KSA    1000
9   10  female     KSA    1000
37  38  female     KSA    1000
41  42  female     KSA    1000
46  47  female     KSA    1000
('KSA', 'female', np.int64(1500))
    Id  Gender Country  Amount
39  40  female     KSA    1500
42  43  female     KSA    1500
47  48  female     KSA    1500
50  51  female     KSA    1500
('KSA', 'female', np.int64(2000))
    Id  Gender Country  Amount
40  41  female     KSA    2000
51  52  female     KSA    2000
('KSA', 'female', np.int64(3000))
    Id  Gender Country  Amount
44  45  female     KSA    3000
49  50  female     KSA    3000
('KSA', 'male', np.int64(1500))
   Id Gender Country  Amount
0   1   male     KSA    1500
5   6   male     KSA    1500
('KSA', 'male', np.int64(2000))
    Id Gender Country  Amount
1    2   male     KSA    2000
33  34   male     KSA    2000
('KSA', 'male', np.int64(3000))
    Id Gender Country  Amount
2    3   male     KSA    3000
17  18   male     KSA    3000
('Kuwait', 'female', np.int64(1000))
    Id  Gender Country  Amount
35  36  female  Kuwait    1000
('Kuwait', 'female', np.int64(2000))
    Id  Gender Country  Amount
3    4  female  Kuwait    2000
11  12  female  Kuwait    2000
18  19  female  Kuwait    2000
36  37  female  Kuwait    2000
43  44  female  Kuwait    2000
48  49  female  Kuwait    2000
('Kuwait', 'female', np.int64(3000))
    Id  Gender Country  Amount
38  39  female  Kuwait    3000
('Kuwait', 'male', np.int64(1000))
    Id Gender Country  Amount
19  20   male  Kuwait    1000
23  24   male  Kuwait    1000
31  32   male  Kuwait    1000
34  35   male  Kuwait    1000
('Kuwait', 'male', np.int64(1500))
    Id Gender Country  Amount
15  16   male  Kuwait    1500
26  27   male  Kuwait    1500
30  31   male  Kuwait    1500
32  33   male  Kuwait    1500
('Kuwait', 'male', np.int64(2000))
    Id Gender Country  Amount
6    7   male  Kuwait    2000
16  17   male  Kuwait    2000
('UAE', 'female', np.int64(1000))
    Id  Gender Country  Amount
14  15  female     UAE    1000
('UAE', 'female', np.int64(1500))
    Id  Gender Country  Amount
10  11  female     UAE    1500
45  46  female     UAE    1500
('UAE', 'female', np.int64(3000))
    Id  Gender Country  Amount
12  13  female     UAE    3000
('UAE', 'male', np.int64(1000))
    Id Gender Country  Amount
25  26   male     UAE    1000
29  30   male     UAE    1000
('UAE', 'male', np.int64(1500))
    Id Gender Country  Amount
21  22   male     UAE    1500
('UAE', 'male', np.int64(2000))
    Id Gender Country  Amount
8    9   male     UAE    2000
13  14   male     UAE    2000
24  25   male     UAE    2000
28  29   male     UAE    2000
('UAE', 'male', np.int64(3000))
    Id Gender Country  Amount
7    8   male     UAE    3000
20  21   male     UAE    3000
22  23   male     UAE    3000
27  28   male     UAE    3000

In [7]:
ss = df.groupby('Gender')['Id'].count()
ss

Gender
female    25
male      27
Name: Id, dtype: int64

In [10]:
gs = df.groupby(['Country' , 'Gender' ])['Id'].count()
gs

Country  Gender
KSA      female    13
         male       6
Kuwait   female     8
         male      10
UAE      female     4
         male      11
Name: Id, dtype: int64

In [14]:
ga = df.groupby('Country')['Amount'].mean()
ga

Country
KSA       1789.473684
Kuwait    1666.666667
UAE       2033.333333
Name: Amount, dtype: float64

In [18]:
gga = df.groupby(['Country']).agg(mean =('Amount','mean'),sell =('Amount','sum'),number =('Id','count'))
gga

                mean   sell  number
Country
KSA      1789.473684  34000      19
Kuwait   1666.666667  30000      18
UAE      2033.333333  30500      15