[]
--

In [2]:
import pandas as pd
df = pd.read_csv('Students.csv' , sep=';')
df.head()

   gender  math score  reading score  writing score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [3]:
g = df['gender']
g

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [11]:
rows = df[5:20]
print(rows)

    gender  math score  reading score  writing score
5   female          71             83             78
6   female          88             95             92
7     male          40             43             39
8     male          64             64             67
9   female          38             60             50
10    male          58             54             52
11    male          40             52             43
12  female          65             81             73
13    male          78             72             70
14  female          50             53             58
15  female          69             75             78
16    male          88             89             86
17  female          18             32             28
18    male          46             42             46
19  female          54             58             61

In [18]:
students = df[['gender' , 'math score']]
students1 = students[1:4 +1]
print(students1)

   gender  math score
1  female          69
2  female          90
3    male          47
4    male          76

loc
---

In [21]:
rwosloc= df.loc[[1,4,55]]
print(rwosloc)

    gender  math score  reading score  writing score
1   female          69             90             88
4     male          76             78             75
55  female          33             41             43

In [24]:
gender = df.loc[[1,77,888],['gender' , 'reading score']]
print(gender)

     gender  reading score
1    female             90
77     male             78
888  female             65

In [37]:
gender11 = df.loc[1:2,['gender' ,'reading score']]
print(gender11)

   gender  reading score
1  female             90
2  female             95

In [33]:
gender2 = df.loc[:,['gender' ,'reading score']]
gender2.head(999)

     gender  reading score
0    female             72
1    female             90
2    female             95
3      male             57
4      male             78
..      ...            ...
994    male             63
995  female             99
996    male             55
997  female             71
998  female             78

[999 rows x 2 columns]

iloc
---

In [35]:
res = df.iloc[[1,3,22]]
print(res)

    gender  math score  reading score  writing score
1   female          69             90             88
3     male          47             57             44
22    male          44             54             53

In [41]:
res_student = df.iloc[1:9 , [0,2]]
print(res_student)

   gender  reading score
1  female             90
2  female             95
3    male             57
4    male             78
5  female             83
6  female             95
7    male             43
8    male             64

مقارنة
--

In [53]:
print('[]')
dd = df[1:3]
print(dd)
print('loc')
loc = df.loc[1:3]
print(loc)
print('iloc')
iloc = df.iloc[1:3]
print(iloc)

[]
   gender  math score  reading score  writing score
1  female          69             90             88
2  female          90             95             93
loc
   gender  math score  reading score  writing score
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
iloc
   gender  math score  reading score  writing score
1  female          69             90             88
2  female          90             95             93