In [1]:
import pandas as pd
df = pd.read_csv('Students_exams_error.csv')
df1 = pd.read_csv('Students_exams_cols_cleanup.csv')
df.head(10)

   gender math score  reading score  writing score
0  female         72           72.0           74.0
1     NaN         69           90.0           88.0
2  female         90           95.0           93.0
3    male         47            NaN           44.0
4    male        abc            NaN           75.0
5  female         71            NaN          500.0
6  female         88           95.0           92.0
7     NaN         40           43.0           39.0
8    male     delete           64.0           67.0
9  female         38           60.0           50.0

تنظيف الاعمدة
--

In [2]:
col = df1.columns
col

Index(['Gender', 'Math Score', 'Reading Score', 'Writing Score'], dtype='object')

In [3]:
df1.columns = [col.lower().replace(" ", "_") for col in df1.columns]
print(df1.columns)

Index(['gender', 'math_score', 'reading_score', 'writing_score'], dtype='object')

In [4]:
df1.head()

   gender  math_score  reading_score  writing_score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

استكشاف البيانات Data Discovery
--

In [5]:
df.head(10)

   gender math score  reading score  writing score
0  female         72           72.0           74.0
1     NaN         69           90.0           88.0
2  female         90           95.0           93.0
3    male         47            NaN           44.0
4    male        abc            NaN           75.0
5  female         71            NaN          500.0
6  female         88           95.0           92.0
7     NaN         40           43.0           39.0
8    male     delete           64.0           67.0
9  female         38           60.0           50.0

In [6]:
df.shape

(1000, 4)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         998 non-null    object
 1   math score     1000 non-null   object
 2   reading score  997 non-null    float64
 3   writing score  997 non-null    float64
dtypes: float64(2), object(2)
memory usage: 31.4+ KB

In [8]:
df.isnull()

     gender  math score  reading score  writing score
0     False       False          False          False
1      True       False          False          False
2     False       False          False          False
3     False       False           True          False
4     False       False           True          False
..      ...         ...            ...            ...
995   False       False          False          False
996   False       False          False          False
997   False       False          False          False
998   False       False          False          False
999   False       False          False          False

[1000 rows x 4 columns]

In [9]:
df.isnull().sum()

gender           2
math score       0
reading score    3
writing score    3
dtype: int64

تنظيف البيانات Data Cleaning
--

In [10]:
df.head(10)

   gender math score  reading score  writing score
0  female         72           72.0           74.0
1     NaN         69           90.0           88.0
2  female         90           95.0           93.0
3    male         47            NaN           44.0
4    male        abc            NaN           75.0
5  female         71            NaN          500.0
6  female         88           95.0           92.0
7     NaN         40           43.0           39.0
8    male     delete           64.0           67.0
9  female         38           60.0           50.0

In [11]:
df['math score'] = pd.to_numeric(df['math score'] , errors = 'coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         998 non-null    object
 1   math score     998 non-null    float64
 2   reading score  997 non-null    float64
 3   writing score  997 non-null    float64
dtypes: float64(3), object(1)
memory usage: 31.4+ KB

In [12]:
df.fillna({'gender' : 'unknow'} , inplace=True)
df.head(10)

   gender  math score  reading score  writing score
0  female        72.0           72.0           74.0
1  unknow        69.0           90.0           88.0
2  female        90.0           95.0           93.0
3    male        47.0            NaN           44.0
4    male         NaN            NaN           75.0
5  female        71.0            NaN          500.0
6  female        88.0           95.0           92.0
7  unknow        40.0           43.0           39.0
8    male         NaN           64.0           67.0
9  female        38.0           60.0           50.0

In [18]:
cols = ['math score', 'reading score', 'writing score']

for col in cols:
    df[col] = df[col].fillna(df[col].mean())
df.head(10)

   gender  math score  reading score  writing score
0  female   72.000000      72.000000           74.0
1  unknow   69.000000      90.000000           88.0
2  female   90.000000      95.000000           93.0
3    male   47.000000      69.158475           44.0
4    male   66.081162      69.158475           75.0
5  female   71.000000      69.158475           75.0
6  female   88.000000      95.000000           92.0
7  unknow   40.000000      43.000000           39.0
8    male   66.081162      64.000000           67.0
9  female   38.000000      60.000000           50.0

In [14]:
df['writing score'] = df['writing score'].where(df['writing score']<=100,75)

In [15]:
df.head(10)

   gender  math score  reading score  writing score
0  female   72.000000      72.000000           74.0
1  unknow   69.000000      90.000000           88.0
2  female   90.000000      95.000000           93.0
3    male   47.000000      69.158475           44.0
4    male   66.081162      69.158475           75.0
5  female   71.000000      69.158475           75.0
6  female   88.000000      95.000000           92.0
7  unknow   40.000000      43.000000           39.0
8    male   66.081162      64.000000           67.0
9  female   38.000000      60.000000           50.0