In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("Students_exams.csv")
df

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [20]:
df = pd.read_csv("Students_exams.csv" , sep="," , usecols=['gender','math score'] , nrows= 10 )
df

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76
5  female          71
6  female          88
7    male          40
8    male          64
9  female          38

In [21]:
df.shape

(10, 2)

In [28]:
df2 = pd.read_csv("Students.csv" , sep=";")
df.tail()

   gender  math score
5  female          71
6  female          88
7    male          40
8    male          64
9  female          38

In [29]:
df.head(3)

   gender  math score
0  female          72
1  female          69
2  female          90

In [47]:
cols = ['gender' , "math" , 'reading' , 'writing']
df3 = pd.read_csv("Students_no_cols.csv" , names=cols)
df3

     gender  math  reading  writing
0    female    72       72       74
1    female    69       90       88
2    female    90       95       93
3      male    47       57       44
4      male    76       78       75
..      ...   ...      ...      ...
995  female    88       99       95
996    male    62       55       55
997  female    59       71       65
998  female    68       78       77
999  female    77       86       86

[1000 rows x 4 columns]