In [1]:
import pandas as pd

In [2]:
dff = pd.DataFrame({
    'name':['khalid','ahmed','fwaz','seed'],
    'age':[15,34,23,55],
    'test':['A+' , 'C-' , 'B+' , 'D-']
})
dff

     name  age test
0  khalid   15   A+
1   ahmed   34   C-
2    fwaz   23   B+
3    seed   55   D-

In [7]:
dff1 = dff.melt(id_vars=['name'])
dff1

   variable   value
0      name  khalid
1      name   ahmed
2      name    fwaz
3      name    seed
4       age      15
5       age      34
6       age      23
7       age      55
8      test      A+
9      test      C-
10     test      B+
11     test      D-

In [18]:
dff2 = dff.melt(id_vars=['name'] , var_name='A' , value_name='B')
dff2

     name     A   B
0  khalid   age  15
1   ahmed   age  34
2    fwaz   age  23
3    seed   age  55
4  khalid  test  A+
5   ahmed  test  C-
6    fwaz  test  B+
7    seed  test  D-

In [24]:
dff2.sort_values(by='A')

     name     A   B
0  khalid   age  15
1   ahmed   age  34
2    fwaz   age  23
3    seed   age  55
4  khalid  test  A+
5   ahmed  test  C-
6    fwaz  test  B+
7    seed  test  D-

In [25]:
dff = pd.DataFrame({
    'name':['khalid','ahmed','fwaz','seed'],
    'age':[15,34,23,55]
})
dff

     name  age
0  khalid   15
1   ahmed   34
2    fwaz   23
3    seed   55

In [31]:
dff.sort_values(by='age').reset_index(drop=True)

     name  age
0  khalid   15
1    fwaz   23
2   ahmed   34
3    seed   55