In [2]:
import pandas as pd
df = pd.read_json("movies.json")
print(df)

                                      title  year  \
0                After Dark in Central Park  1900
1      Boarding School Girls' Pajama Parade  1900
2            Buffalo Bill's Wild West Parad  1900
3                                    Caught  1900
4                      Clowns Spinning Hats  1900
...                                     ...   ...
28790                             Bumblebee  2018
28791                     Welcome to Marwen  2018
28792                     Holmes and Watson  2018
28793                   On the Basis of Sex  2018
28794                             Destroyer  2018

                                                    cast  \
0                                                     []
1                                                     []
2                                                     []
3                                                     []
4                                                     []
...                                                  ...
28790  [Hailee Steinfeld, John Cena, Jorge Lendeborg ...
28791  [Steve Carell, Leslie Mann, Diane Kruger, Falk...
28792  [Will Ferrell, John C. Reilly, Rebecca Hall, R...
28793  [Felicity Jones, Armie Hammer, Justin Theroux,...
28794  [Nicole Kidman, Tatiana Maslany, Sebastian Sta...

                                     genres
0                                        []
1                                        []
2                                        []
3                                        []
4                                        []
...                                     ...
28790  [Action, Adventure, Science Fiction]
28791                      [Fantasy, Drama]
28792             [Action, Mystery, Comedy]
28793                    [Biography, Drama]
28794                     [Crime, Thriller]

[28795 rows x 4 columns]

In [3]:
df

,title,year,cast,genres
0,After Dark in Central Park,1900,[],[]
1,Boarding School Girls' Pajama Parade,1900,[],[]
2,Buffalo Bill's Wild West Parad,1900,[],[]
3,Caught,1900,[],[]
4,Clowns Spinning Hats,1900,[],[]
...,...,...,...,...
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [4]:
df.head(5)

                                  title  year cast genres
0            After Dark in Central Park  1900   []     []
1  Boarding School Girls' Pajama Parade  1900   []     []
2        Buffalo Bill's Wild West Parad  1900   []     []
3                                Caught  1900   []     []
4                  Clowns Spinning Hats  1900   []     []

In [5]:
df.tail(20)

,title,year,cast,genres
28775,The Favourite,2018,"[Emma Stone, Rachel Weisz, Olivia Colman, Nich...","[Biography, Drama]"
28776,Anna and the Apocalypse,2018,"[Ella Hunt, Malcolm Cumming, Marli Siu, Sarah ...","[Horror, Musical, Comedy]"
28777,If Beale Street Could Talk,2018,"[Kiki Layne, Stephan James, Teyonah Parris, Re...","[Drama, Romance]"
28778,Mary Queen of Scots,2018,"[Saoirse Ronan, Margot Robbie, Jack Lowden, Ma...","[Historical, Drama]"
28779,Under the Silver Lake,2018,"[Andrew Garfield, Riley Keough, Topher Grace, ...","[Noir, Crime, Thriller]"
28780,The Silence,2018,"[Miranda Otto, Stanley Tucci, John Corbett]","[Drama, Thriller]"
28781,This One's for the Ladies,2018,"[C-Pudding, Poundcake, Tyga & Raw Dawg, Sweet ...",[Documentary]
28782,Ben Is Back,2018,"[Lucas Hedges, Julia Roberts, Kathryn Newton, ...",[Drama]
28783,Mortal Engines,2018,"[Hera Hilmar, Robert Sheehan, Hugo Weaving, Ji...","[Science Fiction, Action, Adventure]"
28784,Spider-Man: Into the Spider-Verse,2018,"[Shameik Moore, Hailee Steinfeld, Mahershala A...","[Animated, Superhero, Action, Comedy]"
28785,The Mule,2018,"[Clint Eastwood, Bradley Cooper, Laurence Fish...","[Drama, Crime, Biography]"
28786,Vice,2018,"[Christian Bale, Amy Adams, Steve Carell, Sam ...","[Biography, Drama]"
28787,Second Act,2018,"[Jennifer Lopez, Vanessa Hudgens, Leah Remini,...","[Romance, Comedy]"
28788,Mary Poppins Returns,2018,"[Emily Blunt, Lin-Manuel Miranda, Ben Whishaw,...","[Musical, Fantasy]"
28789,Aquaman,2018,"[Jason Momoa, Amber Heard, Willem Dafoe, Patri...","[Superhero, Action, Adventure]"
28790,Bumblebee,2018,"[Hailee Steinfeld, John Cena, Jorge Lendeborg ...","[Action, Adventure, Science Fiction]"
28791,Welcome to Marwen,2018,"[Steve Carell, Leslie Mann, Diane Kruger, Falk...","[Fantasy, Drama]"
28792,Holmes and Watson,2018,"[Will Ferrell, John C. Reilly, Rebecca Hall, R...","[Action, Mystery, Comedy]"
28793,On the Basis of Sex,2018,"[Felicity Jones, Armie Hammer, Justin Theroux,...","[Biography, Drama]"
28794,Destroyer,2018,"[Nicole Kidman, Tatiana Maslany, Sebastian Sta...","[Crime, Thriller]"

In [6]:
df.shape

(28795, 4)